-- ─── Taste Profiles ───────────────────────────────────────────────────────────
-- Persistent per-user aesthetic identity. Compounds across trips over time.
-- This is the semantic core of Along — never deleted, always refined.

create table taste_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade unique,

  -- Raw cultural anchors from intake (free-text references)
  anchors jsonb not null default '{}',
  -- e.g. { artists: ["Wolfgang Tillmans"], musicians: ["Arthur Russell"],
  --        restaurants: ["Chez Panisse"], hotels: ["Claska Tokyo"] }

  -- Claude-derived semantic dimensions (0.0–1.0 or string arrays)
  dimensions jsonb not null default '{}',
  -- e.g. { formality: 0.2, density: 0.7, temporality: 0.3,
  --        sociality: 0.6, legibility: 0.15, materiality: ["concrete","linen"] }

  -- Behavioral signatures
  pace text check (pace in ('slow_deep','varied','high_coverage')) default 'varied',
  meal_philosophy text check (meal_philosophy in ('counter','table','street','mixed')) default 'mixed',
  sleep_pattern text check (sleep_pattern in ('early_light','night_owl','flexible')) default 'flexible',
  discovery_mode text check (discovery_mode in ('wander','researched','local_led')) default 'wander',

  -- Raw intake answers preserved verbatim (for re-inference as model improves)
  raw_answers jsonb not null default '[]',

  -- Narrative summary Claude writes about this person (used in trip prompts)
  taste_summary text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index taste_profiles_user_id_idx on taste_profiles(user_id);

-- ─── Trip Intents ─────────────────────────────────────────────────────────────
-- One row per trip planning session. Links taste profile → blueprint.

create table trip_intents (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  blueprint_id uuid references blueprints(id) on delete set null,

  -- Destination
  destination text not null,
  destination_coordinates jsonb, -- { lat, lng }
  destination_country text,

  -- Who's going
  travelers jsonb not null default '[]',
  -- [{ name, user_id (if Along user), taste_profile_id, is_owner }]

  -- Scope options generated by Claude
  scope_options jsonb not null default '[]',
  -- [{ id, title, duration_days, city_count, estimated_cost, tradeoffs, tagline }]
  selected_scope_id text,

  -- Constraints extracted from intake
  date_window jsonb,          -- { earliest, latest, duration_days, is_flexible }
  budget_tier text check (budget_tier in ('budget','mid','luxury','mixed')),
  hard_constraints text[],    -- ["no tours", "must have a washing machine"]
  soft_preferences text[],    -- ["prefer boutique hotels", "love markets"]

  -- Trip state
  status text not null default 'intake'
    check (status in ('intake','scoping','building','refining','confirmed','active','completed')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index trip_intents_owner_id_idx on trip_intents(owner_id);
create index trip_intents_blueprint_id_idx on trip_intents(blueprint_id);

-- updated_at triggers
create trigger taste_profiles_updated_at
  before update on taste_profiles
  for each row execute procedure handle_updated_at();

create trigger trip_intents_updated_at
  before update on trip_intents
  for each row execute procedure handle_updated_at();
